### ISSUE TITLE
Missing modules after install

### ISSUE THREAD

**Issue by karwester** [PetrKorab/Arabica#10]
I tried installing a few times with pip install arabica (Windows), there were no errors but some modules are missing, for example the coffee_break. Here are the modules that got installed:
11/12/2023  09:54    <DIR>          .
11/12/2023  10:21    <DIR>          ..
11/12/2023  09:54            10,748 arabica_freq.py
11/12/2023  09:54            23,228 cappuccino.py
11/12/2023  09:54             1,684 clean_ngram.py
11/12/2023  09:54               146 clean_numbers.py
11/12/2023  09:54             1,850 group.py
11/12/2023  09:54               460 preprocess.py
11/12/2023  09:54               449 stopwords.py
11/12/2023  09:54                77 __init__.py
11/12/2023  09:54    <DIR>          __pycache__

**Comment by PetrKorab** [comment]
Hi @karwester, I’ve just installed current Arabica, and run Jupyter and Python codes with arabica_freq, coffee_break, and cappuccino methods on Collab (python == 3.10.12) and on clean environments with python == 3.10.13, 3.9.18 and 3.8.18,  (windows) in Pycharm and Dataspell. The same for GitHub actions on clean virtual machines for 3.8 and 3.9. 

There seems to be an issue with your Python configuration. Which error does it produce?
