### ISSUE TITLE
Automated tests:

### ISSUE THREAD

**Issue by linuxscout** [PetrKorab/Arabica#11]
requirement for JOSS journal.
Automated tests: 
Are there automated tests or manual steps described so that the functionality of the software can be verified?

**Comment by PetrKorab** [comment]
@linuxscout Yes, they are in the tests folder.

**Comment by linuxscout** [comment]
Thank you, 
I think that the given script is an example, but not an automated tests,
I suggest to add more test examples using unittest.

**Comment by PetrKorab** [comment]
@linuxscout Thanks, I've also added automated tests for each of the main methods using unittest into the Tests folder.

**Comment by linuxscout** [comment]
Ok, Thanks.
