### ISSUE TITLE
Mizani v0.10.0

### ISSUE THREAD

**Issue by benjaminhuus32** [PetrKorab/Arabica#2]
It appears that in the new update of the Mizani package, "multitype_sort" was removed. This causes an import error when I try to pip install the package. I can successfully run the package if I downgrade Mizani to v0.9.2.

**Comment by PetrKorab** [comment]
Many thanks benjaminhuus32.

I updated the requirements in Arabica 1.7.0. 

Have a great day !

**Comment by PetrKorab** [comment]
Many thanks benjaminhuus32.

I updated the requirements in Arabica 1.7.0.

Have a great day !
